-- Seed file for country table
-- 197 countries: 193 UN member states + 2 observers (Vatican, Palestine) + 2 disputed (Kosovo, Taiwan)
-- Recognition types: un_member, observer, disputed, territory

INSERT INTO country (code, name, region, recognition) VALUES
-- Africa (54 UN members)
('DZ', 'Algeria', 'Africa', 'un_member'),
('AO', 'Angola', 'Africa', 'un_member'),
('BJ', 'Benin', 'Africa', 'un_member'),
('BW', 'Botswana', 'Africa', 'un_member'),
('BF', 'Burkina Faso', 'Africa', 'un_member'),
('BI', 'Burundi', 'Africa', 'un_member'),
('CV', 'Cabo Verde', 'Africa', 'un_member'),
('CM', 'Cameroon', 'Africa', 'un_member'),
('CF', 'Central African Republic', 'Africa', 'un_member'),
('TD', 'Chad', 'Africa', 'un_member'),
('KM', 'Comoros', 'Africa', 'un_member'),
('CG', 'Congo', 'Africa', 'un_member'),
('CD', 'Democratic Republic of the Congo', 'Africa', 'un_member'),
('DJ', 'Djibouti', 'Africa', 'un_member'),
('EG', 'Egypt', 'Africa', 'un_member'),
('GQ', 'Equatorial Guinea', 'Africa', 'un_member'),
('ER', 'Eritrea', 'Africa', 'un_member'),
('SZ', 'Eswatini', 'Africa', 'un_member'),
('ET', 'Ethiopia', 'Africa', 'un_member'),
('GA', 'Gabon', 'Africa', 'un_member'),
('GM', 'Gambia', 'Africa', 'un_member'),
('GH', 'Ghana', 'Africa', 'un_member'),
('GN', 'Guinea', 'Africa', 'un_member'),
('GW', 'Guinea-Bissau', 'Africa', 'un_member'),
('CI', 'Ivory Coast', 'Africa', 'un_member'),
('KE', 'Kenya', 'Africa', 'un_member'),
('LS', 'Lesotho', 'Africa', 'un_member'),
('LR', 'Liberia', 'Africa', 'un_member'),
('LY', 'Libya', 'Africa', 'un_member'),
('MG', 'Madagascar', 'Africa', 'un_member'),
('MW', 'Malawi', 'Africa', 'un_member'),
('ML', 'Mali', 'Africa', 'un_member'),
('MR', 'Mauritania', 'Africa', 'un_member'),
('MU', 'Mauritius', 'Africa', 'un_member'),
('MA', 'Morocco', 'Africa', 'un_member'),
('MZ', 'Mozambique', 'Africa', 'un_member'),
('NA', 'Namibia', 'Africa', 'un_member'),
('NE', 'Niger', 'Africa', 'un_member'),
('NG', 'Nigeria', 'Africa', 'un_member'),
('RW', 'Rwanda', 'Africa', 'un_member'),
('ST', 'Sao Tome and Principe', 'Africa', 'un_member'),
('SN', 'Senegal', 'Africa', 'un_member'),
('SC', 'Seychelles', 'Africa', 'un_member'),
('SL', 'Sierra Leone', 'Africa', 'un_member'),
('SO', 'Somalia', 'Africa', 'un_member'),
('ZA', 'South Africa', 'Africa', 'un_member'),
('SS', 'South Sudan', 'Africa', 'un_member'),
('SD', 'Sudan', 'Africa', 'un_member'),
('TZ', 'Tanzania', 'Africa', 'un_member'),
('TG', 'Togo', 'Africa', 'un_member'),
('TN', 'Tunisia', 'Africa', 'un_member'),
('UG', 'Uganda', 'Africa', 'un_member'),
('ZM', 'Zambia', 'Africa', 'un_member'),
('ZW', 'Zimbabwe', 'Africa', 'un_member'),

-- Americas (35 UN members)
('AG', 'Antigua and Barbuda', 'Americas', 'un_member'),
('AR', 'Argentina', 'Americas', 'un_member'),
('BS', 'Bahamas', 'Americas', 'un_member'),
('BB', 'Barbados', 'Americas', 'un_member'),
('BZ', 'Belize', 'Americas', 'un_member'),
('BO', 'Bolivia', 'Americas', 'un_member'),
('BR', 'Brazil', 'Americas', 'un_member'),
('CA', 'Canada', 'Americas', 'un_member'),
('CL', 'Chile', 'Americas', 'un_member'),
('CO', 'Colombia', 'Americas', 'un_member'),
('CR', 'Costa Rica', 'Americas', 'un_member'),
('CU', 'Cuba', 'Americas', 'un_member'),
('DM', 'Dominica', 'Americas', 'un_member'),
('DO', 'Dominican Republic', 'Americas', 'un_member'),
('EC', 'Ecuador', 'Americas', 'un_member'),
('SV', 'El Salvador', 'Americas', 'un_member'),
('GD', 'Grenada', 'Americas', 'un_member'),
('GT', 'Guatemala', 'Americas', 'un_member'),
('GY', 'Guyana', 'Americas', 'un_member'),
('HT', 'Haiti', 'Americas', 'un_member'),
('HN', 'Honduras', 'Americas', 'un_member'),
('JM', 'Jamaica', 'Americas', 'un_member'),
('MX', 'Mexico', 'Americas', 'un_member'),
('NI', 'Nicaragua', 'Americas', 'un_member'),
('PA', 'Panama', 'Americas', 'un_member'),
('PY', 'Paraguay', 'Americas', 'un_member'),
('PE', 'Peru', 'Americas', 'un_member'),
('KN', 'Saint Kitts and Nevis', 'Americas', 'un_member'),
('LC', 'Saint Lucia', 'Americas', 'un_member'),
('VC', 'Saint Vincent and the Grenadines', 'Americas', 'un_member'),
('SR', 'Suriname', 'Americas', 'un_member'),
('TT', 'Trinidad and Tobago', 'Americas', 'un_member'),
('US', 'United States', 'Americas', 'un_member'),
('UY', 'Uruguay', 'Americas', 'un_member'),
('VE', 'Venezuela', 'Americas', 'un_member'),

-- Asia (48 UN members + 1 disputed)
('AF', 'Afghanistan', 'Asia', 'un_member'),
('AM', 'Armenia', 'Asia', 'un_member'),
('AZ', 'Azerbaijan', 'Asia', 'un_member'),
('BH', 'Bahrain', 'Asia', 'un_member'),
('BD', 'Bangladesh', 'Asia', 'un_member'),
('BT', 'Bhutan', 'Asia', 'un_member'),
('BN', 'Brunei', 'Asia', 'un_member'),
('KH', 'Cambodia', 'Asia', 'un_member'),
('CN', 'China', 'Asia', 'un_member'),
('CY', 'Cyprus', 'Asia', 'un_member'),
('GE', 'Georgia', 'Asia', 'un_member'),
('IN', 'India', 'Asia', 'un_member'),
('ID', 'Indonesia', 'Asia', 'un_member'),
('IR', 'Iran', 'Asia', 'un_member'),
('IQ', 'Iraq', 'Asia', 'un_member'),
('IL', 'Israel', 'Asia', 'un_member'),
('JP', 'Japan', 'Asia', 'un_member'),
('JO', 'Jordan', 'Asia', 'un_member'),
('KZ', 'Kazakhstan', 'Asia', 'un_member'),
('KW', 'Kuwait', 'Asia', 'un_member'),
('KG', 'Kyrgyzstan', 'Asia', 'un_member'),
('LA', 'Laos', 'Asia', 'un_member'),
('LB', 'Lebanon', 'Asia', 'un_member'),
('MY', 'Malaysia', 'Asia', 'un_member'),
('MV', 'Maldives', 'Asia', 'un_member'),
('MN', 'Mongolia', 'Asia', 'un_member'),
('MM', 'Myanmar', 'Asia', 'un_member'),
('NP', 'Nepal', 'Asia', 'un_member'),
('KP', 'North Korea', 'Asia', 'un_member'),
('OM', 'Oman', 'Asia', 'un_member'),
('PK', 'Pakistan', 'Asia', 'un_member'),
('PH', 'Philippines', 'Asia', 'un_member'),
('QA', 'Qatar', 'Asia', 'un_member'),
('SA', 'Saudi Arabia', 'Asia', 'un_member'),
('SG', 'Singapore', 'Asia', 'un_member'),
('KR', 'South Korea', 'Asia', 'un_member'),
('LK', 'Sri Lanka', 'Asia', 'un_member'),
('SY', 'Syria', 'Asia', 'un_member'),
('TJ', 'Tajikistan', 'Asia', 'un_member'),
('TH', 'Thailand', 'Asia', 'un_member'),
('TL', 'Timor-Leste', 'Asia', 'un_member'),
('TR', 'Turkey', 'Asia', 'un_member'),
('TM', 'Turkmenistan', 'Asia', 'un_member'),
('AE', 'United Arab Emirates', 'Asia', 'un_member'),
('UZ', 'Uzbekistan', 'Asia', 'un_member'),
('VN', 'Vietnam', 'Asia', 'un_member'),
('YE', 'Yemen', 'Asia', 'un_member'),
-- Disputed - Taiwan
('TW', 'Taiwan', 'Asia', 'disputed'),
-- Observer - Palestine
('PS', 'Palestine', 'Asia', 'observer'),

-- Europe (44 UN members + 1 observer + 1 disputed)
('AL', 'Albania', 'Europe', 'un_member'),
('AD', 'Andorra', 'Europe', 'un_member'),
('AT', 'Austria', 'Europe', 'un_member'),
('BY', 'Belarus', 'Europe', 'un_member'),
('BE', 'Belgium', 'Europe', 'un_member'),
('BA', 'Bosnia and Herzegovina', 'Europe', 'un_member'),
('BG', 'Bulgaria', 'Europe', 'un_member'),
('HR', 'Croatia', 'Europe', 'un_member'),
('CZ', 'Czech Republic', 'Europe', 'un_member'),
('DK', 'Denmark', 'Europe', 'un_member'),
('EE', 'Estonia', 'Europe', 'un_member'),
('FI', 'Finland', 'Europe', 'un_member'),
('FR', 'France', 'Europe', 'un_member'),
('DE', 'Germany', 'Europe', 'un_member'),
('GR', 'Greece', 'Europe', 'un_member'),
('HU', 'Hungary', 'Europe', 'un_member'),
('IS', 'Iceland', 'Europe', 'un_member'),
('IE', 'Ireland', 'Europe', 'un_member'),
('IT', 'Italy', 'Europe', 'un_member'),
('LV', 'Latvia', 'Europe', 'un_member'),
('LI', 'Liechtenstein', 'Europe', 'un_member'),
('LT', 'Lithuania', 'Europe', 'un_member'),
('LU', 'Luxembourg', 'Europe', 'un_member'),
('MT', 'Malta', 'Europe', 'un_member'),
('MD', 'Moldova', 'Europe', 'un_member'),
('MC', 'Monaco', 'Europe', 'un_member'),
('ME', 'Montenegro', 'Europe', 'un_member'),
('NL', 'Netherlands', 'Europe', 'un_member'),
('MK', 'North Macedonia', 'Europe', 'un_member'),
('NO', 'Norway', 'Europe', 'un_member'),
('PL', 'Poland', 'Europe', 'un_member'),
('PT', 'Portugal', 'Europe', 'un_member'),
('RO', 'Romania', 'Europe', 'un_member'),
('RU', 'Russia', 'Europe', 'un_member'),
('SM', 'San Marino', 'Europe', 'un_member'),
('RS', 'Serbia', 'Europe', 'un_member'),
('SK', 'Slovakia', 'Europe', 'un_member'),
('SI', 'Slovenia', 'Europe', 'un_member'),
('ES', 'Spain', 'Europe', 'un_member'),
('SE', 'Sweden', 'Europe', 'un_member'),
('CH', 'Switzerland', 'Europe', 'un_member'),
('UA', 'Ukraine', 'Europe', 'un_member'),
('GB', 'United Kingdom', 'Europe', 'un_member'),
-- Observer - Vatican
('VA', 'Vatican City', 'Europe', 'observer'),
-- Disputed - Kosovo
('XK', 'Kosovo', 'Europe', 'disputed'),

-- Oceania (14 UN members)
('AU', 'Australia', 'Oceania', 'un_member'),
('FJ', 'Fiji', 'Oceania', 'un_member'),
('KI', 'Kiribati', 'Oceania', 'un_member'),
('MH', 'Marshall Islands', 'Oceania', 'un_member'),
('FM', 'Micronesia', 'Oceania', 'un_member'),
('NR', 'Nauru', 'Oceania', 'un_member'),
('NZ', 'New Zealand', 'Oceania', 'un_member'),
('PW', 'Palau', 'Oceania', 'un_member'),
('PG', 'Papua New Guinea', 'Oceania', 'un_member'),
('WS', 'Samoa', 'Oceania', 'un_member'),
('SB', 'Solomon Islands', 'Oceania', 'un_member'),
('TO', 'Tonga', 'Oceania', 'un_member'),
('TV', 'Tuvalu', 'Oceania', 'un_member'),
('VU', 'Vanuatu', 'Oceania', 'un_member');
